# Use postgres/example user/password credentials
version: '3.1'

services:
  database:
    image: mcr.microsoft.com/mssql/server
    container_name: unischedule-db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Qwerty123#123!"
    volumes:
      - './drive:/var/opt/mssql/data'
    ports:
    - "1433:1433"
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$$SA_PASSWORD" -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s

  chrome:
    image: selenium/standalone-chrome
    ports:
      - 4444:4444


  bot:
    image: unischedule:latest    
    container_name: unischedule
    build:
      context: .
    environment:
      CONNECTION_STRING: "Server=database,1433; Database=UniScheduleDB; User ID=sa; Password=Qwerty123#123!; MultipleActiveResultSets=True"
    depends_on:
      database:
        condition: service_healthy
