# Use postgres/example user/password credentials
version: '3.1'

services:
  database:
    image: mcr.microsoft.com/mssql/server
    container_name: unischedule-db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD:
      TZ: "Europe/Moscow"
      DEBIAN_FRONTEND: "noninteractive"
    volumes:
      - './drive:/var/opt/mssql/data'
    ports:
    - "1433:1433"
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$$SA_PASSWORD" -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s

  chrome:
    image: selenium/standalone-chrome
    ports:
      - 4444:4444


  bot:
    image: foxjefisto/unischedule-bot:latest
    container_name: unischedule-bot
    environment:
      CONNECTION_STRING:
    depends_on:
      database:
        condition: service_healthy

  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 unischedule-bot