name: Docker Image CI
env:
  DOCKERHUB_LOGIN: ${{ secrets.DOCKERHUB_LOGIN }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
  SA_PASSWORD: ${{ secrets.SA_PASSWORD }}

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Add Connection String to docker-compose.yaml
      run: sed -i 's/CONNECTION_STRING:/${{ env.CONNECTION_STRING }}' ./UniShedule/docker-compose.yaml
    - name: Add password to docker-compose.yaml
      run: sed -i 's/SA_PASSWORD:/${{ env.SA_PASSWORD }}' ./UniShedule/docker-compose.yaml
    - name: Build the Docker image
      run: docker build ./UniShedule --tag ${{ env.DOCKERHUB_LOGIN }}/unischedule-bot:latest
    - name: Login into DockerHub
      run: docker login -u ${{ env.DOCKERHUB_LOGIN }} -p ${{ env.DOCKERHUB_PASSWORD }}
    - name: Publish the docker image
      run: docker push -a ${{ env.DOCKERHUB_LOGIN }}/unischedule-bot
      
